apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-metrics-cron
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: node-metrics-cron
            image: dev06/one2n:Assignment
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: metrics
              mountPath: /metrics
          restartPolicy: OnFailure
          volumes:
          - name: metrics
            hostPath:
              path: /Users/devanshusingh/Desktop/workspace/code/kubernetes/one2n-assignment/metrics-data
              type: Directory